- name: Reboot host
  shell: "sleep 1 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait host
  wait_for:
    sleep: 10
    host: "{{ ansible_host }}"
    port: 22
    delay: 1
    timeout: 150
  connection: local

